#!/bin/env sh
PATH="/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin" 
cd "$(dirname "$0")"; exec 4>&1; ECHO(){ echo "${@}" >&4; }
[ "$ECHO" == "Ok" ] || { exec 3<>"/dev/null";exec 0<&3;exec 1>&3;exec 2>&3; }

#基本配置
URL="http://ddns.local:1253/namemapv2"
NAME="${1:-$HOSTNAME}"
TAGT="$2"
MTTL="$3"

#简易参数请求
curl --connect-timeout 3 -X "POST" -d "SIMPLEPM;$NAME;V4HOST;$TAGT;$MTTL" "$URL" &
curl --connect-timeout 3 -X "POST" -d "SIMPLEPM;mrdbser;V4CLUT" "$URL" &

exit 0
